# .github/workflows/readme-build.yml
name: README build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write  # Allows workflow to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1      # keep commit history shallow
          persist-credentials: true  # use GITHUB_TOKEN for push auth by default

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME:   ${{ secrets.USER_NAME }}
        run: python today.py

      - name: Configure commit user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Updated README" -a || echo "No changes to commit"

      - name: Push changes
        run: git push
