name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1      # keep at least one commit
        # persist-credentials stays true by default, so push auth works
  
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: Configure pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
  
    - name: Install dependencies
      run: python -m pip install -r cache/requirements.txt
  
    - name: Update README file
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        USER_NAME:   ${{ secrets.USER_NAME }}
      run: python today.py
  
    - name: Configure Git for push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
  
    - name: Commit changes
      run: |
        git add .
        git commit -m "Updated README" -a || echo "No changes to commit"
  
    - name: Push changes
      run: git push origin HEAD:${{ github.ref_name }}  # Push back to the triggering branch
