name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *'    # runs every 6 hours
  workflow_dispatch:       # allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-dateutil lxml requests

      - name: Generate SVG stats
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME:   ${{ secrets.USER_NAME }}
        run: python today.py

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add light_mode.svg dark_mode.svg
          git commit -m "chore: update stats [skip ci]" || echo "No changes to commit"
          git push
